version: 2
updates:
  - directory: /divinv-frontend
    package-ecosystem: npm
    schedule:
        interval: weekly
    open-pull-requests-limit: 10
  - directory: divinv-backend
    package-ecosystem: gradle
    schedule:
      interval: weekly
    open-pull-requests-limit: 10
