version: 2
updates:
  - directory: /divinv-frontend
    package-ecosystem: npm
    schedule:
        interval: daily
  - directory: divinv-backend
    package-ecosystem: gradle
    schedule:
      interval: daily
